### ISSUE TITLE
Blade directive and caching

### ISSUE THREAD

**Issue by OwenMelbz** [zschuessler/laravel-route-to-class#1]
Hey :) liking the work so far!

I'm just thinking that it would be nice to turn this into a blade directive? That way you'd benefit from laravels directive caching too!

Would appeal to people who don't like calling global functions from within templates

**Comment by zschuessler** [comment]
Thanks Owen for the suggestions, much appreciated!

I'm pushing a new major release with this update, seems others on Reddit wanted a Blade directive as well.

Some other good ideas in the feedback, here it is for reference:


> Looks very helpful. I always miss the helpful body classes in Wordpress sites when I use Laravel.
> 
> One package I like that does something similar is https://laravel-breadcrumbs.readthedocs.io/en/latest/start.html#define-your-breadcrumbs. It's similar in that it deconstructs routes at the segment-by-segment level, and at each segment adds new bread crumbs. Something like this could be similar, where there are a base set of classes (maybe for the user who is logged in, etc), and each route segment adds more (the page slug or ID, or entity ID, etc). Definitely found that breadcrumb package easy to use, and you could make a blade directive to echo out the classes when you are ready for them.
> 
> I bet middlewares could also be used to make this workflow simple.
> 
> Another idea is you could use this for more than just body classes. It could fit into a larger package that helps you to generate classes for any element in a simple way. like ClassManager::addClass('footer', 'two-column') and then in your template <footer class="@classes('footer')">


I doubt I add a `@classes` directive since it goes beyond the scope of the package's intent (body classes). Plus Laravel already has support for that kind of thing, for the most part, with its own directives.

**Comment by zschuessler** [comment]
New release adds both Blade directive and Facade support:

https://github.com/zschuessler/laravel-route-to-class/releases/tag/2.1.0
